export * from './area-documento.controller';
export * from './area.controller';
export * from './campo.controller';
export * from './catalogo.controller';
export * from './documento-documento-evento.controller';
export * from './documento.controller';
export * from './responsable.controller';
export * from './tipo-documento.controller';
export * from './usuario.controller';
